trigger: none

variables:
- group: the-pizza-database-fe-var

pool:
  vmImage: ubuntu-latest

steps:
- script: npm install
  displayName: install packages

- script: npm run build
  displayName: build app
  env:
    VITE_API_URL: $(VITE_API_URL)
    VITE_API_KEY: $(VITE_API_KEY)

- script: ls -R
  displayName: 'List all files'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: 'dist'
    azure_static_web_apps_api_token: $(STATIC_WEB_APP_TOKEN)
  displayName: deploy static web app